import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";

const harmoniaSans = localFont({
  src: [
    {
      path: "fonts/HarmoniaSansProCyr-Regular.otf", // Absolute path from `public`
      weight: "300"
    }
  ],
  variable: "--font-harmonia-sans",
});
const theSeasons = localFont({
  src: [
    {
      path: "fonts/Fontspring-DEMO-theseasons-bd.otf", // Absolute path from `public`
      weight: "900"
    },
    {
      path: "fonts/Fontspring-DEMO-theseasons-lt.otf", // Absolute path from `public`
      weight: "400"
    }
  ],
  variable: "--font-the-seasons",
})

export const metadata: Metadata = {
  title: "Santa Phone Calls",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${harmoniaSans.variable} bg-[url('/santa.jpeg')] bg-cover bg-center bg-no-repeat h-screen w-full ${theSeasons.variable} antialiased`}
      >

      <Header />
        {children}
      </body>
    </html>
  );
}
