import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const harmoniaSans = localFont({
  src: [
    {
      path: "../public/fonts/HarmoniaSansProCyr-Regular.otf", // Absolute path from `public`
      weight: "300"
    }
  ],
  variable: "--font-harmonia-sans",
});
const theSeasons = localFont({
  src: [
    {
      path: "../public/fonts/Fontspring-DEMO-theseasons-bd.otf", // Absolute path from `public`
      weight: "900"
    },
    {
      path: "../public/fonts/Fontspring-DEMO-theseasons-lt.otf", // Absolute path from `public`
      weight: "400"
    }
  ],
  variable: "--font-the-seasons",
})

export const metadata: Metadata = {
  title: "Santa Phone Calls",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${harmoniaSans.variable}  ${theSeasons.variable} antialiased`}
      >
      <Toaster position="top-right" reverseOrder={false} />
        {children}
      </body>
    </html>
  );
}
